apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular-app
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: jemesbond/angular:v1
        ports:
        - containerPort: 80
